#name: Greetings
#
#on: [pull_request, issues]
#
#jobs:
#  greeting:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/first-interaction@v1
#      with:
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        issue-message: 'Message that will be displayed on users'' first issue'
#        pr-message: 'Message that will be displayed on users'' first pr'

name: Run Tests
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run test
      - run: npm run test-codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
